name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  docker_base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'base.Dockerfile'
              - 'fastapi/requirements.txt'
              - 'streamlit/requirments.txt'
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        if: steps.changes.outputs.src == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: steps.changes.outputs.src == 'true'
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.changes.outputs.src == 'true'
      -
        name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
        if: steps.changes.outputs.src == 'true'
      -
        name: Build and push
        uses: docker/build-push-action@v6
        if: steps.changes.outputs.src == 'true'
        with:
          context: .
          file: base.Dockerfile
          push: true
          tags: pondered/base_structudoc:latest,pondered/base_structudoc:${{ steps.timestamp.outputs.timestamp }}
          platforms: linux/amd64,linux/arm64


  docker:
    runs-on: ubuntu-latest
    needs: docker_base
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: pondered/structudoc:latest,pondered/structudoc:${{ steps.timestamp.outputs.timestamp }}
          platforms: linux/amd64,linux/arm64
